// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfybxxwcvrdiqnkwdjqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmeWJ4eHdjdnJkaXFua3dkanFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTg4MjgsImV4cCI6MjA2NTk5NDgyOH0.hhQFIbIkxLi46zAMMy_2Xhe-QAG_hPPEk0pSrfwcjKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);